version: "3"
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "4040:4040"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
      - postgres
      - redis
